name: Java Workflow
on: [push, pull_request]

jobs:
  call-java-workflow:
    uses: brightsparklabs/github-actions/.github/workflows/java.yml@master
    # Since all of our workflows are called from the same organisation, we can use the `inherit`
    # keyword to pass secrets to the called workflow.
    secrets: inherit
    # These permissions are required for Dependabot to merge PRs.
    permissions:
      contents: write
      pull-requests: write
